function z=phi_hh(alpha,delta,phi,teta)
% эта функция задает формулу 2.51 главы 2 диссертации

z=(sin(delta).^2).*(cos(alpha).^2).*(sin(phi).^2).*(sin(teta).^2)+...
  (sin(delta).^2).*(sin(alpha).^2).*(cos(phi).^2)+(cos(delta).^2).*...
  (sin(phi).^2).*(cos(teta).^2)-0.5.*sin(2.*delta).*cos(alpha).*...
  (sin(phi).^2).*sin(2.*teta)-0.5.*sin(2.*delta).*sin(alpha).*...
   sin(2.*phi).*cos(teta)+0.5.*(sin(delta).^2).*sin(2.*alpha).*...
   sin(2.*phi).*sin(teta);
end
